'use strict';

/**
 * lib/worker-entry.js
 *
 * PHASE 3 — Unified worker thread entry point.
 *
 * Handles all CPU-heavy tasks dispatched by WorkerPool.js:
 *   'optimize'    – grid/random search over strategy parameters
 *   'backtest'    – single-run backtest on given OHLCV data
 *   'robustness'  – full suite (MC + IS/OOS + walk-forward + sensitivity)
 *   'montecarlo'  – Monte Carlo simulation only (lighter)
 *
 * Receives OHLCV data via SharedArrayBuffer (zero-copy, no JSON parse).
 * Results are posted back via the transferred MessagePort provided by WorkerPool.
 *
 * DO NOT require() this file directly — it is spawned by WorkerPool.js.
 */

const path = require('path');
const { parentPort } = require('worker_threads');

// Heavy modules are loaded once per worker lifetime (cached by require)
const StrategyRegistry = require(path.join(__dirname, '../services/strategy/StrategyRegistry'));
const BacktestEngine   = require(path.join(__dirname, '../analytics/Engine'));
const QuantReporter    = require(path.join(__dirname, '../analytics/Reporter'));
const Optimizer        = require(path.join(__dirname, '../analytics/Optimizer'));

const { buildTradeList }         = require(path.join(__dirname, './TradeBuilder'));
const { unpackOHLCV }            = require(path.join(__dirname, './WorkerPool'));
const {
    monteCarlo,
    fullRobustnessReport,
} = require(path.join(__dirname, '../analytics/RobustnessEngine'));

// ─── Shared helper ────────────────────────────────────────────────────────────

/**
 * Unpack SAB → run ImbaAlgo → BacktestEngine → return { ohlcv, processed, engineOpts }
 */
function prepareBacktest(sab, strategyOpts, engineOpts, strategyName = 'imba-algo') {
    const ohlcv  = unpackOHLCV(sab);
    const entry  = StrategyRegistry.get(strategyName);
    if (!entry) throw new Error(`Unknown strategy: ${strategyName}`);

    const strategyInstance = new entry.Cls(strategyOpts || {});
    
    // Heikin Ashi transformation logic if strategy requires it
    let feedOhlcv = ohlcv;
    if (entry.useHeikinAshi) {
        const HeikinAshi = require("../lib/HeikinAshi");
        feedOhlcv = HeikinAshi.transform(ohlcv);
    }
    
    const result = strategyInstance.generateSignals(feedOhlcv);
    const raw    = buildTradeList(result.candles);

    const engine = new BacktestEngine(engineOpts || {});
    const { report, trades: processed } = engine.run(raw);

    return { ohlcv, raw, processed, report, engine, engineOpts };
}

// ─── Task handlers ────────────────────────────────────────────────────────────

/**
 * 'backtest' — single run, returns analysis + processed trades.
 */
function runBacktest({ sab, engineOpts, strategyOpts, strategyName }) {
    const { processed, report } = prepareBacktest(sab, strategyOpts, engineOpts, strategyName);

    if (!processed.length) return { error: 'No trades generated by strategy' };

    const analysis = QuantReporter.generateReport(report);
    return { analysis, trades: processed };
}

/**
 * 'optimize' — grid search over ImbaAlgo parameters, returns ranked results.
 */
function runOptimize({ sab, engineOpts, topN, minTrades, mode, verbose, fixedParams, paramSpace, port }) {
    const ohlcv = unpackOHLCV(sab);

    if (!ohlcv.close || ohlcv.close.length < 50) {
        return { error: 'Insufficient candle data (need ≥ 50 bars)' };
    }

    return Optimizer.runGrid(ohlcv, engineOpts || {}, {
        topN:        topN        ?? 10,
        minTrades:   minTrades   ?? 3,
        mode:        mode        ?? 'fast',
        verbose:     verbose     ?? true,
        fixedParams: fixedParams ?? {},
        paramSpace:  paramSpace,
        onProgress:  (progress) => {
            if (port) port.postMessage({ type: 'progress', ...progress });
        }
    });
}

/**
 * 'robustness' — full anti-overfitting suite.
 */
function runRobustness({ sab, engineOpts, strategyOpts, opts, strategyName }) {
    const { processed, ohlcv } = prepareBacktest(sab, strategyOpts, engineOpts, strategyName);

    if (!processed.length) return { error: 'No trades generated by strategy' };

    return fullRobustnessReport(processed, engineOpts || {}, {
        ...(opts || {}),
        // Pass ohlcv + buildTrades for parameter sensitivity analysis
        ohlcv,
        buildTrades: buildTradeList,
        bestParams:  strategyOpts,
    });
}

/**
 * 'montecarlo' — lighter Monte Carlo simulation only.
 */
function runMonteCarlo({ sab, engineOpts, strategyOpts, opts, strategyName }) {
    const { processed } = prepareBacktest(sab, strategyOpts, engineOpts, strategyName);

    if (!processed.length) return { error: 'No trades generated by strategy' };

    return monteCarlo(processed, engineOpts || {}, opts || {});
}

// ─── Task dispatcher ──────────────────────────────────────────────────────────

const HANDLERS = {
    backtest:   runBacktest,
    optimize:   runOptimize,
    robustness: runRobustness,
    montecarlo: runMonteCarlo,
};

// Receive tasks from WorkerPool via transferred MessagePort
parentPort.on('message', ({ taskName, payload, opts, port }) => {
    try {
        const handler = HANDLERS[taskName];
        if (!handler) {
            port.postMessage({ error: `Unknown task: ${taskName}` });
            port.close();
            return;
        }

        // Merge payload (contains sab) and opts (engine/strategy params)
        const result = handler({ ...payload, ...opts, port });
        port.postMessage({ result });
    } catch (err) {
        port.postMessage({ error: err.message });
    } finally {
        port.close();
    }
});
